republishers:
- topic: "/rosout"
  msg_type: "rosgraph_msgs/Log"
  mappings:
  - field: "msg"
    mapping_type: "single_field"
    out:
      topic: "/inorbit/custom_data/0"
      key: "rosout_msg"

- topic: "/diagnostics"
  msg_type: "diagnostic_msgs/DiagnosticArray"
  mappings:
  - field: "status"
    mapping_type: "array_of_fields"
    mapping_options:
      fields: ["level", "hardware_id"]
      filter: 'lambda x: (x.level == 1 or x.level == 2)'
    out:
      topic: "/inorbit/diagnostics_test"
      key: "diagnostics_status"

- topic: "/hardware/battery"
  msg_type: "BatteryState"
  mappings:
  - field: "state"
    mapping_type: "json_of_fields"
    mapping_options:
      fields: ["voltage", "current", "power_supply_status", "power_supply_health"]
    out:
      topic: "/inorbit/custom_data/0"
      key: "battery_state"